# Generated by Django 2.1 on 2019-05-15 07:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_eng', models.CharField(blank=True, default='', max_length=150)),
                ('title_org', models.CharField(blank=True, default='', max_length=150)),
                ('audience', models.IntegerField(default=0)),
                ('release', models.DateField(blank=True, default=datetime.datetime.now)),
                ('thumb_url', models.URLField(blank=True, default='')),
                ('poster_url', models.URLField(blank=True, default='')),
                ('running_time', models.IntegerField(default=0)),
                ('director', models.CharField(blank=True, default='', max_length=45)),
                ('film_rating', models.CharField(blank=True, default='', max_length=45)),
                ('actor1', models.CharField(blank=True, default='', max_length=45)),
                ('actor2', models.CharField(blank=True, default='', max_length=45)),
                ('actor3', models.CharField(blank=True, default='', max_length=45)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
