# Generated by Django 2.1 on 2019-05-15 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='summary',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor1',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor2',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor3',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='film_rating',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumb_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_org',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
